### ISSUE TITLE
[Feat] 온보딩 뷰 작성

### ISSUE THREAD

**Issue by FpRaArNkK** [node-cafe-iOS-presso/iOS#5]
# 📝 작업 내용
온보딩 플로우를 작성합니다

## ✔️ To-Do
- [x] 스플래시 화면 작성
- [x] 로그인 화면 작성
- [x] 애플 로그인 테스트

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
